import { NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';

const SYSTEM_PROMPT = `You are helping reconstruct the original quiz answers that generated a brand discovery brief. The brief was created by an AI that analyzed and synthesized form answers — it did not quote them directly. Your job is to work backwards from the brief text to reconstruct the most likely original answers.

For each reconstructed answer:
- State the most likely answer with HIGH / MEDIUM / LOW confidence
- If multiple answers are plausible, list all options in order of likelihood with reasoning
- Flag any inferences that could be wrong
- Note which brief phrases led to each reconstruction

The quiz had these fields — reconstruct each one:

DEADLINES & SCOPE:
- deadline: April 10 deadline status (single select: "Yes — April 10 is locked" / "It's shifted" / "No hard deadline")
- phase1Deliverables: What needs to exist by deadline (multi select): Pitch deck / Landing page / Product mockup or screenshot / Logo only / Social presence / Demo or animation
- phase2Deliverables: Full scope beyond deadline (multi select): Full website / Product UI skin / Marketing assets / Brand guidelines doc / Email and comms templates / Motion or animation direction / Print or physical

BUDGET & WORKING TERMS:
- budget: Budget (open text)
- brandUsers: Who uses the brand system (multi select): Developers / Non-designers using AI tools / In-house or contracted designers / Founders doing it themselves
- signoff: Sign-off person (open text)
- workingPrefs: Working preferences (open text)

TECHNICAL DETAILS & NAMING:
- subBrands: Sub-brand status (single select): "One name MMLABS is everything" / "Separate products exist or are planned" / "Not decided yet"
- subBrandsNote: Sub-brand names if any (open text)
- mmMeaning: MM meaning (open text)
- brandPerception: MM association goal (open text)
- platforms: Platform (multi select): Web desktop / Web mobile / iOS app / Android app / Nothing built yet
- languages: Language support (single select): "English only" / "Yes multilingual" / "Not sure yet"
- languagesNote: Languages if multilingual (open text)
- existingBuild: Existing build status (single select): "Greenfield" / "Wireframes exist" / "Prototype exists" / "Live product"
- existingBuildNote: Existing build detail (open text)

VISUAL DIRECTION:
- critterCommitment: Critter commitment (single select): "Very committed" / "Open to see alternatives" / "Loose idea"
- characterRole: Critter role (single select): "Face of brand mascot" / "AI agent" / "Situational" / "Decorative texture"
- visualAvoid: Additional visual avoidance (open text)

BRAND PERSONALITY:
- pair1: Lawyer feel pair: left = "Calm and trusted" / right = "Sharp and impressive"
- pair2: Client feel pair: left = "Warm and safe" / right = "Clear and efficient"
- pair3: Brand energy pair: left = "Quiet confidence" / right = "Visible ambition"
- pair4: Visual density pair: left = "Minimal and airy" / right = "Rich and textured"
- threeWords: Three word feeling (open text)
- anythingElse: Anything else (open text)

OPTIONAL:
- colorPrefs: Color instincts (open text)
- fontPrefs: Typography instincts (open text)
- brandInspo: Competitive visual references (open text)

Note: the brief was generated by an AI that was instructed to ANALYZE answers, not quote them. So a brief saying 'the immigrant founder story becomes the core differentiator' likely came from answers confirming the founding story matters, not from someone writing that exact phrase. Work backwards through that layer of synthesis.

Also note: the app may have had additional fields or details added during development that are not listed above — if the brief references something that doesn't map to any field above, flag it as a potentially unknown field and include it as a finding.

Return your analysis as JSON with this exact structure:
{
  "fields": [
    {
      "fieldName": "deadline",
      "label": "April 10 deadline status",
      "category": "DEADLINES & SCOPE",
      "reconstructedValue": "the most likely answer",
      "confidence": "HIGH" | "MEDIUM" | "LOW",
      "alternatives": ["other possible answers if any"],
      "reasoning": "why this value was chosen",
      "briefExcerpt": "the phrase(s) from the brief that led to this"
    }
  ],
  "unknownFields": [
    {
      "briefExcerpt": "text that doesn't map to known fields",
      "possibleMeaning": "what it might represent"
    }
  ]
}

Return ONLY valid JSON. No markdown, no code fences, no preamble.`;

export async function POST(request: Request) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ error: 'API key not configured' }, { status: 500 });
  }

  const password = request.headers.get('x-recovery-password');
  if (!password || password !== process.env.RECOVERY_PASSWORD) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  let body: { briefText: string };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
  }

  if (!body.briefText || body.briefText.trim().length < 50) {
    return NextResponse.json({ error: 'Brief text too short to reconstruct from' }, { status: 400 });
  }

  const anthropic = new Anthropic({ apiKey });

  try {
    const response = await anthropic.messages.create({
      model: 'claude-4-sonnet-20250514',
      max_tokens: 4000,
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: 'user',
          content: `Here is the generated brief text to reconstruct from:\n\n${body.briefText}`,
        },
      ],
    });

    const text = response.content[0].type === 'text' ? response.content[0].text : '';
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    const result = jsonMatch ? JSON.parse(jsonMatch[0]) : JSON.parse(text);

    return NextResponse.json(result);
  } catch (err) {
    console.error('Reconstruction API call failed:', err);
    return NextResponse.json(
      { error: 'Reconstruction failed', details: err instanceof Error ? err.message : 'Unknown' },
      { status: 500 }
    );
  }
}
